name: Wayback Scraper

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL or domain to scrape (e.g., www.google.com)'
        required: true
        default: 'www.google.com'  # Default value for the URL
      from_date:
        description: 'The starting year for the Wayback Machine (e.g., 2020)'
        required: true
        default: '2020'  # Default start date
      to_date:
        description: 'The ending year for the Wayback Machine (e.g., 2023)'
        required: true
        default: '2023'  # Default end date

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests colorama

    - name: Run Wayback Scraper
      run: |
        python wayback.py ${{ github.event.inputs.url }} ${{ github.event.inputs.from_date }} ${{ github.event.inputs.to_date }}
